# Generated by Django 6.1.1 on 2026-09-27 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OUShareMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ou_name', models.CharField(help_text='مثال: MATH-PRIM أو SCIENCE-SEC أو ADMIN', max_length=255, unique=True, verbose_name='اسم OU')),
                ('share_slug', models.CharField(help_text='مثال: math-prim أو science-sec — يجب أن يتطابق مع SMB_MOUNTS في .env', max_length=100, verbose_name='معرف المشاركة (Slug)')),
                ('share_path', models.CharField(help_text='مثال: /app/shares/math-prim — المسار حيث يتم mount المجلد داخل الحاوية', max_length=500, verbose_name='مسار المشاركة داخل الحاوية')),
                ('display_name', models.CharField(blank=True, help_text='مثال: مواد الرياضيات الابتدائية — سيظهر للمعلم في لوحة التحكم', max_length=255, verbose_name='اسم العرض')),
                ('description', models.TextField(blank=True, help_text='مثال: مجلد مواد الرياضيات للمرحلة الابتدائية - يحتوي على كتب، فيديوهات، وأوراق عمل', verbose_name='وصف')),
                ('is_active', models.BooleanField(default=True, help_text='إذا كان غير نشط، لن يظهر للمدرسين المنتمين لهذا OU', verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
            ],
            options={
                'verbose_name': 'ربط OU بالمشاركة',
                'verbose_name_plural': 'روابط OU بالمشاركات',
                'ordering': ['ou_name'],
                'indexes': [models.Index(fields=['ou_name'], name='school_port_ou_name_cef81f_idx'), models.Index(fields=['share_slug'], name='school_port_share_s_57fae0_idx')],
            },
        ),
    ]
