# Generated by Django 6.1.1 on 2026-09-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_portal', '0002_ousharemapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='ousharemapping',
            name='smb_username',
            field=models.CharField(blank=True, help_text='مثال: hazem — اتركه فارغاً لاستخدام بيانات الاعتماد الافتراضية', max_length=100, verbose_name='اسم مستخدم SMB'),
        ),
        migrations.AddField(
            model_name='ousharemapping',
            name='smb_password',
            field=models.CharField(blank=True, help_text='مثال: 12345 — اتركها فارغة لاستخدام بيانات الاعتماد الافتراضية', max_length=255, verbose_name='كلمة مرور SMB'),
        ),
        migrations.AddField(
            model_name='ousharemapping',
            name='smb_domain',
            field=models.CharField(blank=True, help_text='مثال: ALMANARSCHOOL — اتركه فارغاً لاستخدام الدومين الافتراضي', max_length=100, verbose_name='دومين SMB'),
        ),
    ]